name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드를 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js 설정 (Next.js의 환경에 맞는 Node.js 버전 사용)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Next.js 권장 버전
          cache: 'npm'     # npm 캐싱 활성화

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. Lint 검사
      - name: Run Lint
        run: npm run lint

      # 5. Next.js 빌드
      - name: Build Next.js application
        run: npm run build

      # 6. 테스트 실행 (필요한 경우)
      - name: Run Tests
        run: npm test
